mvn clean install -f C:/Apps/MyEcoApp/config-server/pom.xml
mvn clean install -f C:/Apps/MyEcoApp/registry-service/pom.xml
mvn clean install -f C:/Apps/MyEcoApp/gateway-service/pom.xml
mvn clean install -f C:/Apps/MyEcoApp/auth-service/pom.xml
mvn clean install -f C:/Apps/MyEcoApp/user-service/pom.xml
mvn clean install -f C:/Apps/MyEcoApp/challenge-service/pom.xml
mvn clean install -f C:/Apps/MyEcoApp/challenge-user-service/pom.xml
mvn clean install -f C:/Apps/MyEcoApp/contest-service/pom.xml
mvn clean install -f C:/Apps/MyEcoApp/player-service/pom.xml
