FROM alpine-jdk:base
MAINTAINER GauthierRobert
RUN apk --no-cache add netcat-openbsd
COPY jar/user-service-0.0.1-SNAPSHOT.jar /opt/lib/
COPY entrypoint/User-service-entrypoint.sh /opt/bin/User-service-entrypoint.sh
RUN dos2unix /opt/bin/User-service-entrypoint.sh
RUN chmod 755 /opt/bin/User-service-entrypoint.sh
EXPOSE 16014
