security:
  oauth2:
    client:
      clientId: challenge-service
      clientSecret: 1234
      accessTokenUri: http://localhost:16015/uaa/oauth/token
      grant-type: client_credentials
      scope: server
server:
  servlet:
    context-path: /challenge
  port: 16017

feign:
  hystrix:
    enabled: true