security:
  oauth2:
    client:
      clientId: user-service
      clientSecret: 1234
      accessTokenUri: http://auth-service:16015/uaa/oauth/token
      grant-type: client_credentials
      scope: server
server:
  servlet:
    context-path: /user
  port: 16014

feign:
  hystrix:
    enabled: true
spring:
  kafka:
    group-id: USER